#==================================================================
# react-native-permissions 관련
#------------------------------------------------------------------
require_relative '../node_modules/react-native-permissions/scripts/setup.rb'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

#node_require('react-native/scripts/react_native_pods.rb')
#node_require('react-native-permissions/scripts/setup.rb')  
#==================================================================
  
platform :ios, min_ios_version_supported
use_modular_headers!
prepare_react_native_project!

#==================================================================
# react-native-permissions 관련 : 필요시 주석해제해야함 
#------------------------------------------------------------------
setup_permissions([
	# 'AppTrackingTransparency',
	# 'Bluetooth',
	# 'Calendars',
	# 'CalendarsWriteOnly',
	'Camera',
	# 'Contacts',
	# 'FaceID',
	#'LocationAccuracy',
	#'LocationAlways',
	#'LocationWhenInUse',
	# 'MediaLibrary',
	# 'Microphone',
	# 'Motion',
	'Notifications',
	# 'PhotoLibrary',
	# 'PhotoLibraryAddOnly',
	# 'Reminders',
	# 'Siri',
	# 'SpeechRecognition',
	# 'StoreKit',
])
#==================================================================
#use_frameworks! :linkage => :static   # Firebase 대응 (항상 적용)

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

target 'HmPrmClient' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
